### ISSUE TITLE
Installation does not work

### ISSUE THREAD

**Issue by vromero** [ssorj/quiver#10]
Fedora 24
```
dnf install -y 'dnf-command(copr)' && \
dnf copr enable -y jross/ssorj && \
dnf install -y qpid-proton-c && \
dnf install -y quiver
```
```
Error: nothing provides libqpid-proton.so.8()(64bit) needed by quiver-0-0.1.20161116.8bc457a.fc24.x86_64
```

**Comment by vromero** [comment]
Although it seems to work in 23

**Comment by ssorj** [comment]
I'm reproducing this problem.  I'm not sure what it is yet.  I'll let you know when I figure it out.

**Comment by ssorj** [comment]
Hi, Victor.  I made a new build, and it's working for me.  Would you try it out?

**Comment by vromero** [comment]
[Worked](https://hub.docker.com/r/vromero/ssorj-quiver/builds/bw8rhabgf7agtx7cpvfic3u/) like a charm:
