### ISSUE TITLE
Package quiver for Fedora 27

### ISSUE THREAD

**Issue by orpiske** [ssorj/quiver#33]
Hello, 
I am trying to integrate Quiver as a test agent into [Maestro](https://github.com/maestro-performance) and I noticed that the package for Fedora 27 is missing on COPR. Would it be possible to trigger a build and package it for Fedora 27 as well?

Thanks

**Comment by ssorj** [comment]
F27 builds are now available.

https://copr.fedorainfracloud.org/coprs/jross/ssorj/build/751380/
