### ISSUE TITLE
Use a separate jar for each client instead of one Uber Jar

### ISSUE THREAD

**Issue by tabish121** [ssorj/quiver#5]
Looks like the project currently creates a single Uber jar for all the JMS clients which seems to be creating some trouble when trying to use snapshots of the various clients.  I think the trouble might lay in the fact that with only one jar you won't know what version of the dependencies each client brings in ultimately ends up in the final jar.  For instance upstream Qpid JMS is on Netty 4.1.5.final but I believe the Artemis core client will fight to bring in an old 4.0.x version of Netty which will probably result in errors at runtime for Qpid JMS.

By having a single uber jar for each JMS client you will have better version isolation for the various dependencies each one brings in.

**Comment by ssorj** [comment]
Got it - that makes sense.  I'll split them out.

**Comment by ssorj** [comment]
https://github.com/ssorj/quiver/commit/8d7b19b9523198af9e554f42ea396e536945a0e8
